In [1]:
import collections
import inspect

import numpy as np
import pandas as pd

import graphiclog

In [2]:
graphiclog.__file__

'/home/administrator/code/python/graphiclog/graphiclog/__init__.py'

In [3]:
dir(graphiclog)

['Bed',
 'BedSequence',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'bed',
 'sequence',
 'utils']

In [4]:
transforms = {c : graphiclog.utils.string2array for c in ['depth_m', 'grain_size_mm']}

beds = pd.read_csv('../data/AllBedsWithProfiles.csv', converters=transforms)
beds.head()

name  count        collection          eod  eodnum      tops       th  \
0  Marnoso 1      1  Marnoso-Arenacea  basin plain       0  22.81684  0.31082   
1  Marnoso 1      1  Marnoso-Arenacea  basin plain       0  22.50602  0.60931   
2  Marnoso 1      1  Marnoso-Arenacea  basin plain       0  21.89671  0.10463   
3  Marnoso 1      1  Marnoso-Arenacea  basin plain       0  21.79208  0.11694   
4  Marnoso 1      1  Marnoso-Arenacea  basin plain       0  21.67514  0.13232   

   gs_tops_mm  snd_shl  mean_gs_mm  max_gs_mm        ng        ar  \
0    0.115051      1.0    0.116073   0.117046  0.520514  0.021978   
1    0.001000      0.0    0.001000   0.001000  0.520514  0.021978   
2    0.125380      1.0    0.125380   0.125380  0.520514  0.021978   
3    0.001000      0.0    0.001000   0.001000  0.520514  0.021978   
4    0.134306      1.0    0.150073   0.160420  0.520514  0.021978   

                                    depth_m  \
0  [22.81684, 22.70297, 22.53372, 22.50602]   
1                      [22.50602, 21.89671]   
2                      [21.89671, 21.79208]   
3                      [21.79208, 21.67514]   
4  [21.67514, 21.63514, 21.56744, 21.54282]   

                                  grain_size_mm  
0   [0.115051, 0.1157124, 0.1170462, 0.1170462]  
1                                [0.001, 0.001]  
2                        [0.1253796, 0.1253796]  
3                                [0.001, 0.001]  
4  [0.1343059, 0.1446953, 0.1604199, 0.1604199]

In [5]:
for i, (name, grp) in enumerate(beds.groupby('name')):
    if i > 0:
        break
    
    bedseq = graphiclog.BedSequence.from_dataframe(grp, topcol='tops', thickcol='th',
                                         datacols=['th', 'mean_gs_mm', 'depth_m', 'grain_size_mm'],
                                         metacols=['name', 'collection', 'eod', 'eodnum'])
    
    print(bedseq.values, bedseq.metadata)
    

[[4.30171000e+00 1.90957896e-01 2.26699400e+02 1.09779500e-01]
 [4.30171000e+00 1.90957896e-01 2.26947100e+02 1.72378300e-01]
 [4.30171000e+00 1.90957896e-01 2.28003600e+02 1.85330900e-01]
 ...
 [8.59930000e-01 5.56285467e-03 1.03743400e+02 8.60539500e-03]
 [8.59930000e-01 5.56285467e-03 1.04019800e+02 9.45795000e-03]
 [8.59930000e-01 5.56285467e-03 1.04062800e+02 9.45795000e-03]] {'name': 'Amazon 931B', 'collection': 'Amazon', 'eod': 'fan', 'eodnum': 1}


/home/administrator/code/python/graphiclog/graphiclog/sequence.py:126: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['base'] = df[topcol] - df[thickcol]


In [6]:
beds[beds.name == 'Amazon 931B']

name  count collection  eod  eodnum       tops       th  \
2836  Amazon 931B     63     Amazon  fan       1  103.20288  0.85993   
2837  Amazon 931B     63     Amazon  fan       1  104.06281  0.52825   
2838  Amazon 931B     63     Amazon  fan       1  104.59106  0.86606   
2839  Amazon 931B     63     Amazon  fan       1  105.45712  2.78249   
2840  Amazon 931B     63     Amazon  fan       1  108.23961  0.23341   
2841  Amazon 931B     63     Amazon  fan       1  108.47302  3.16332   
2842  Amazon 931B     63     Amazon  fan       1  111.63634  0.37470   
2843  Amazon 931B     63     Amazon  fan       1  112.01104  0.13514   
2844  Amazon 931B     63     Amazon  fan       1  112.14618  0.19654   
2845  Amazon 931B     63     Amazon  fan       1  112.34272  0.42382   
2846  Amazon 931B     63     Amazon  fan       1  112.76654  0.17813   
2847  Amazon 931B     63     Amazon  fan       1  112.94467  0.35627   
2848  Amazon 931B     63     Amazon  fan       1  113.30094  0.35010   
2849  Amazon 931B     63     Amazon  fan       1  113.65104  0.28255   
2850  Amazon 931B     63     Amazon  fan       1  113.93359  0.27641   
2851  Amazon 931B     63     Amazon  fan       1  114.21000  0.07985   
2852  Amazon 931B     63     Amazon  fan       1  114.28985  0.40541   
2853  Amazon 931B     63     Amazon  fan       1  114.69526  0.12284   
2854  Amazon 931B     63     Amazon  fan       1  114.81810  0.56509   
2855  Amazon 931B     63     Amazon  fan       1  115.38319  1.66459   
2856  Amazon 931B     63     Amazon  fan       1  117.04778  0.27640   
2857  Amazon 931B     63     Amazon  fan       1  117.32418  0.15357   
2858  Amazon 931B     63     Amazon  fan       1  117.47775  0.32553   
2859  Amazon 931B     63     Amazon  fan       1  117.80328  0.47297   
2860  Amazon 931B     63     Amazon  fan       1  118.27625  0.31941   
2861  Amazon 931B     63     Amazon  fan       1  118.59566  0.07984   
2862  Amazon 931B     63     Amazon  fan       1  118.67550  0.19041   
2863  Amazon 931B     63     Amazon  fan       1  118.86591  0.06757   
2864  Amazon 931B     63     Amazon  fan       1  118.93348  0.20884   
2865  Amazon 931B     63     Amazon  fan       1  119.14232  0.35626   
...           ...    ...        ...  ...     ...        ...      ...   
3000  Amazon 931B     63     Amazon  fan       1  211.02608  0.11671   
3001  Amazon 931B     63     Amazon  fan       1  211.14279  0.58353   
3002  Amazon 931B     63     Amazon  fan       1  211.72632  0.35625   
3003  Amazon 931B     63     Amazon  fan       1  212.08257  0.40539   
3004  Amazon 931B     63     Amazon  fan       1  212.48796  0.34398   
3005  Amazon 931B     63     Amazon  fan       1  212.83194  0.59581   
3006  Amazon 931B     63     Amazon  fan       1  213.42775  0.09828   
3007  Amazon 931B     63     Amazon  fan       1  213.52603  0.05528   
3008  Amazon 931B     63     Amazon  fan       1  213.58131  0.09214   
3009  Amazon 931B     63     Amazon  fan       1  213.67345  0.06141   
3010  Amazon 931B     63     Amazon  fan       1  213.73486  0.29483   
3011  Amazon 931B     63     Amazon  fan       1  214.02969  0.17200   
3012  Amazon 931B     63     Amazon  fan       1  214.20169  0.84151   
3013  Amazon 931B     63     Amazon  fan       1  215.04320  0.92135   
3014  Amazon 931B     63     Amazon  fan       1  215.96455  0.52825   
3015  Amazon 931B     63     Amazon  fan       1  216.49280  1.41273   
3016  Amazon 931B     63     Amazon  fan       1  217.90553  0.42998   
3017  Amazon 931B     63     Amazon  fan       1  218.33551  2.29724   
3018  Amazon 931B     63     Amazon  fan       1  220.63275  0.58968   
3019  Amazon 931B     63     Amazon  fan       1  221.22243  0.38696   
3020  Amazon 931B     63     Amazon  fan       1  221.60939  0.74323   
3021  Amazon 931B     63     Amazon  fan       1  222.35262  1.23461   
3022  Amazon 931B     63     Amazon  fan       1  223.58723  0.48525   
3023  Amazon 931B     63     Amazon  fan       1  224

In [7]:
len(bedseq), bedseq.nsamples, bedseq.nfeatures

(194, 709, 4)

In [8]:
bedseq[0]

Interval({'data': {'th': 4.30171000000001, 'mean_gs_mm': 0.190957896323552, 'depth_m': array([226.6994, 226.9471, 228.0036, 229.2566, 230.6264, 231.0011]), 'grain_size_mm': array([0.1097795, 0.1723783, 0.1853309, 0.1967622, 0.2108319, 0.2108319])}, 'top': Position({'middle': 226.69937000000002, 'units': 'm'}), 'base': Position({'middle': 222.39766, 'units': 'm'}), 'description': '', 'components': []})

In [9]:
bedseq[0].max_field('grain_size_mm')

0.2108319

In [10]:
bedseq.max_field('grain_size_mm')

0.2534653

In [11]:
bedseq[1]

Interval({'data': {'th': 0.4340699999999911, 'mean_gs_mm': 0.150108088110957, 'depth_m': array([226.2653, 226.3759, 226.6646, 226.6994]), 'grain_size_mm': array([0.001    , 0.1543449, 0.191401 , 0.191401 ])}, 'top': Position({'middle': 226.2653, 'units': 'm'}), 'base': Position({'middle': 225.83123, 'units': 'm'}), 'description': '', 'components': []})

In [27]:
bedseq[4]

Interval({'data': {'th': 0.6019499999999879, 'mean_gs_mm': 0.001, 'depth_m': array([225.0246, 225.6265]), 'grain_size_mm': array([0.001, 0.001])}, 'top': Position({'middle': 225.02455, 'units': 'm'}), 'base': Position({'middle': 224.42260000000002, 'units': 'm'}), 'description': '', 'components': []})

In [12]:
b = graphiclog.Bed(top=1.0, base=0.0, data={'a' : 1, 'b' : [1,2,3]})

In [13]:
b

Interval({'data': {'a': 1, 'b': [1, 2, 3]}, 'top': Position({'middle': 1.0, 'units': 'm'}), 'base': Position({'middle': 0.0, 'upper': 0.0, 'lower': 0.0, 'units': 'm'}), 'description': '', 'components': []})

In [14]:
b.values

array([[1, 1],
       [1, 2],
       [1, 3]])

In [15]:
len(np.array([1,2,3]))

3

In [16]:
len(set([1,2,3,4,4,3,2,1,1]))

4

In [17]:
b['a'], b['b']

(1, [1, 2, 3])

In [18]:
b.min_field('a'), b.max_field('a')

(1, 1)

In [19]:
b.min_field('b'), b.max_field('b')

(1, 3)

In [20]:
b2 = graphiclog.Bed(top=2.0, base=1.0, data={'a' : [1,1,2], 'b' : [3,2,1]})
b._compatible_with(b2)

True

In [21]:
b3 = graphiclog.Bed(top=2.0, base=1.0, data={'a' : [1,1,2], 'b' : [3,2,1], 'c' : 5})
b._compatible_with(b3)

False

In [22]:
xp = np.arange(5,10)
fp = np.random.rand(5)

x = np.arange(10)

np.interp(x, xp, fp, left=np.nan, right=np.nan)

array([       nan,        nan,        nan,        nan,        nan,
       0.7311968 , 0.011929  , 0.85329947, 0.06926609, 0.06622975])

In [23]:
import lasio

df = lasio.read('/home/administrator/Downloads/204-20-1_logs.las').df()

df

Header section Parameter regexp=~P was not found.


CALI  DENC  DENS  DTC  DTS       GR  NEUT  PEF  RDEP  RMIC  RSHAL  \
DEPTH                                                                          
400.0000    NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
400.1524    NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
400.3048    NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
400.4572    NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
400.6096    NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
400.7620    NaN   NaN   NaN  NaN  NaN  39.1675   NaN  NaN   NaN   NaN    NaN   
400.9144    NaN   NaN   NaN  NaN  NaN  36.6688   NaN  NaN   NaN   NaN    NaN   
401.0668    NaN   NaN   NaN  NaN  NaN  34.0544   NaN  NaN   NaN   NaN    NaN   
401.2192    NaN   NaN   NaN  NaN  NaN  34.8124   NaN  NaN   NaN   NaN    NaN   
401.3716    NaN   NaN   NaN  NaN  NaN  36.6110   NaN  NaN   NaN   NaN    NaN   
401.5240    NaN   NaN   NaN  NaN  NaN  38.6646   NaN  NaN   NaN   NaN    NaN   
401.6764    NaN   NaN   NaN  NaN  NaN  38.5262   NaN  NaN   NaN   NaN    NaN   
401.8288    NaN   NaN   NaN  NaN  NaN  39.0555   NaN  NaN   NaN   NaN    NaN   
401.9812    NaN   NaN   NaN  NaN  NaN  37.9613   NaN  NaN   NaN   NaN    NaN   
402.1336    NaN   NaN   NaN  NaN  NaN  33.7517   NaN  NaN   NaN   NaN    NaN   
402.2860    NaN   NaN   NaN  NaN  NaN  29.0802   NaN  NaN   NaN   NaN    NaN   
402.4384    NaN   NaN   NaN  NaN  NaN  27.7703   NaN  NaN   NaN   NaN    NaN   
402.5908    NaN   NaN   NaN  NaN  NaN  31.6901   NaN  NaN   NaN   NaN    NaN   
402.7432    NaN   NaN   NaN  NaN  NaN  35.0849   NaN  NaN   NaN   NaN    NaN   
402.8956    NaN   NaN   NaN  NaN  NaN  35.3006   NaN  NaN   NaN   NaN    NaN   
403.0480    NaN   NaN   NaN  NaN  NaN  32.7428   NaN  NaN   NaN   NaN    NaN   
403.2004    NaN   NaN   NaN  NaN  NaN  31.4014   NaN  NaN   NaN   NaN    NaN   
403.3528    NaN   NaN   NaN  NaN  NaN  31.2052   NaN  NaN   NaN   NaN    NaN   
403.5052    NaN   NaN   NaN  NaN  NaN  31.7895   NaN  NaN   NaN   NaN    NaN   
403.6576    NaN   NaN   NaN  NaN  NaN  30.6035   NaN  NaN   NaN   NaN    NaN   
403.8100    NaN   NaN   NaN  NaN  NaN  28.8812   NaN  NaN   NaN   NaN    NaN   
403.9624    NaN   NaN   NaN  NaN  NaN  25.5472   NaN  NaN   NaN   NaN    NaN   
404.1148    NaN   NaN   NaN  NaN  NaN  23.6672   NaN  NaN   NaN   NaN    NaN   
404.2672    NaN   NaN   NaN  NaN  NaN  21.1690   NaN  NaN   NaN   NaN    NaN   
404.4196    NaN   NaN   NaN  NaN  NaN  19.7319   NaN  NaN   NaN   NaN    NaN   
...         ...   ...   ...  ...  ...      ...   ...  ...   ...   ...    ...   
2540.4580   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2540.6104   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2540.7628   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2540.9152   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.0676   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.2200   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.3724   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.5248   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.6772   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.8296   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2541.9820   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.1344   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.2868   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.4392   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.5916   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.7440   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2542.8964   NaN   NaN   NaN  NaN  NaN      NaN   NaN  NaN   NaN   NaN    NaN   
2543.0488  

In [24]:
x = np.arange(400, 2545, 0.5)

d = {}

for c in df.columns:
    d[c] = np.interp(x, df.index.values, df[c].values, left=np.nan, right=np.nan

SyntaxError: unexpected EOF while parsing (<ipython-input-24-8ad66ed37e9a>, line 6)