In [2]:
d = {'a': 0, 'b': 1, 'c': 2}

for k, v in d.items():
    if k == 'b':
        continue
    print(k, v)

a 0
c 2


In [3]:
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)

print(np.delete(a, 2, axis=1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(np.insert(np.delete(a, 2, axis=1), 2, [2, 6, 10], axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
list(d.keys()).index('b')

1

In [12]:
len(d.keys())

3

In [13]:
x = np.array([[1,2,3]])
x.shape

(1, 3)

In [14]:
np.repeat(x, 2, axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
from graphiclog import utils

In [17]:
utils.safelen(None)

1